### ISSUE TITLE
Question about refunding

### ISSUE THREAD

**Issue by meeshoogendoorn** [buckaroo-it/Shopware_6#24]
We were on plugin version 1.2.2 and now we are on 1.2.4 on Shopware 6.4.7.0, But when we placed a refund normally we could edit the totalPrice with an input. Is this not possible anymore? when i place a refund with the new plugin version i always place a refund of the full order and i cant edit the total anymore. Am i missing something?

<img width="1039" alt="Screenshot 2021-12-13 at 08 46 17" src="https://user-images.githubusercontent.com/55089200/145772119-e8e145dd-d803-426d-afd9-f7e4126dcaae.png">

**Comment by meeshoogendoorn** [comment]
Hi @Buckaroo-Rens Did u guys already looked into the issue?

**Comment by Buckaroo-Rens** [comment]
No, we are in our current sprint working on support for the newest SW version and this question is part of our testing procedure.

**Comment by meeshoogendoorn** [comment]
@Buckaroo-Rens any idea when the new version will be finished?

**Comment by Buckaroo-Rens** [comment]
That could be next year even, since we have a release freeze. You guys also know it's an possibility to refund from the Buckaroo Plaza? This will then also update the status in Shopware.

**Comment by meeshoogendoorn** [comment]
Okay great, We will see the update after the holidays!

**Comment by Buckaroo-Rens** [comment]
Refund issue should have been fixed/adjusted in our latest release.
