### ISSUE TITLE
Finalize page not loaded correctly, order not set to paid

### ISSUE THREAD

**Issue by MelvinAchterhuis** [buckaroo-it/Shopware_6#32]
In `src/Storefront/Controller/PushController.php` the function `finalizeBuckaroo` doesn't work as expected. The request variables in my dump are uppercase, however the variables are set with lowercase:

```
$status        = $request->request->get('brq_statuscode');
$statusMessage = $request->request->get('brq_statusmessage');
$orderId       = $request->request->get('ADD_orderId');
```

These variables are all null. When I dump the variables you can see the difference:

![Screenshot 2022-03-07 at 10 47 46](https://user-images.githubusercontent.com/26538915/157007659-54b420f5-510a-4907-bc6c-f9ebeac277a2.png)

```
dd(
	$request->request->get('brq_statuscode'), 
	$request->request->get('BRQ_STATUSCODE')
);
```

![Screenshot 2022-03-07 at 10 45 09](https://user-images.githubusercontent.com/26538915/157006952-93da54f0-098d-40bd-a080-6b5ad49df78d.png)

Because the variables are null it results in a empty finalize page and the order isn't set to paid in Shopware.

**Comment by Buckaroo-Rens** [comment]
@MelvinAchterhuis This seems something with the setup at Buckaroo Plaza side. Can you send me a email on r.gerritsen@buckaroo.nl it's not a setting i can change right now since the 'credentials' are also used on a live environment.

**Comment by Buckaroo-Rens** [comment]
Issue was a setting on Buckaroo Plaza side. Fixed.
