### ISSUE TITLE
Uncaught PHP Exception TypeError: "round(): Argument #1 ($num) must be of type int|float, string given"

### ISSUE THREAD

**Issue by MelvinAchterhuis** [buckaroo-it/Shopware_6#33]
When placing an order that contains a product that has a price with more than 2 decimals, the following error is thrown:

``request.CRITICAL: Uncaught PHP Exception TypeError: "round(): Argument #1 ($num) must be of type int|float, string given" at /var/domains/customer/application/vendor/store.shopware.com/buckaroopayments/src/Storefront/Controller/PushController.php line 202 {"exception":"[object] (TypeError(code: 0): round(): Argument #1 ($num) must be of type int|float, string given at /var/domains/customer/application/vendor/store.shopware.com/buckaroopayments/src/Storefront/Controller/PushController.php:202)"} []``

**Comment by Buckaroo-Rens** [comment]
Issue fixed in new release
