### ISSUE TITLE
The plugin crashes shopware 6.4.9.0

### ISSUE THREAD

**Issue by rickschippers** [buckaroo-it/Shopware_6#37]
When updating to shopware 6.4.9.0 on my development environment `bin/console` created a segmentation fault. This already happens in the composer update step that tries to run `system:update:prepare`.

The segmentation fault was caused by xdebug, which is running on my dev environment. Disabling xdebug fixed the segmentation fault, and showed the underlying cause. The process is trying to use an infinite amount of memory, probably caused by some looping issue.

![screenshot](https://i.imgur.com/Aw8iNhq.png)

As you can see here the memory limit of 2GB is reached by just running `bin/console` to get a list of commands. Increasing the memory to 4GB, 8GB, or 16GB, just makes it break at that limit.

For testing purposes this is being done a clean new shopware 6.4.9.0 installation with just the buckaroo shopware plugin installed, nothing else.  I tested with php 8.1, 8.0 and 7.4, which all showed the same results. 

Also tried versions 1.3.0 and 1.2.4 of the plugin, with similar results. 

We did a bit of digging yesterday, the culprit seems to be in the the payment handlers somewhere. But haven't completely pinned the it down yet. 

This issue is preventing the shopware 6.4.9.0 update for now.

**Comment by Buckaroo-Rens** [comment]
Hello @rickschippers thanks for your issue. At this moment we are in process of testing 6.4.9.0 so will take this issue while testing it.

**Comment by Buckaroo-Rens** [comment]
Issue fixed in new release.
