### ISSUE TITLE
[BP-1726] Unclear error message is shown to customer when (iDeal) payment provider is down.

### ISSUE THREAD

**Issue by nielsVoogt** [buckaroo-it/Shopware_6#45]
We received an email from a client that showed a screenshot of a customer that couldn't finish the checkout process. She sent our client the following screenshot:

<img width="280" alt="image" src="https://user-images.githubusercontent.com/8556818/168771485-9bc7cec5-81c4-4526-9e1b-a3e917606492.png">

After investigating this issue, the moment of her not being able to pay using iDeal coincided with downtime of iDeal (16th of may between 10:00 and 11:00). The error message returned when this occurs has `Issuer` as message, not very useful for the customer.

The error message should be more user-friendly and descriptive.

**Comment by Buckaroo-Rene** [comment]
@nielsVoogt Thank you for sharing this with us. We agree that this message needs to be more user-friendly and descriptive.
We've created a ticket internally to solve this in one of the upcoming sprints. Currently this is on our backlog.

**Comment by Buckaroo-Rens** [comment]
issue is released.
