### ISSUE TITLE
changed redirect behaviour from Buckaroo

### ISSUE THREAD

**Issue by meeshoogendoorn** [buckaroo-it/Shopware_6#81]
When i call the `/store-api/handle-payment` with ideal issuer i will be redirected to the following url at Buckaroo `https://testcheckout.buckaroo.nl/html/testresult.aspx`.

This is all okay and as it should but i sent a few params with the `/handle-payment` call see following parameters:

```js
 const handledPaymentResponse = await handlePayment(
          order.id,
          routing.getUrl(`/order-success?orderId=${order.id}`),
          routing.getUrl(
            `/order-failed?orderId=${order.id}`
          ),
          apiInstance
        );
```

The redirect is an relative url and buckaroo will redirect to the following page resulting in a 404: `https://testcheckout.buckaroo.nl/order-success?orderId=SOME_ORDER_ID`

In the past Buckaroo would redirect me back to the storefront `domain.com/order-success?orderId=SOME_ORDER_ID`

Is this a problem on buckaroo's end or in Shopware 6?

I am using Buckaroo Plugin 1.4.0 and SW6 6.4.15.2

**Comment by meeshoogendoorn** [comment]
This also means that if i set the parameter for finishUrl to `https://google.com/` it will redirect me to google with a successful payment.

**Comment by Buckaroo-Rens** [comment]
Sorry @meeshoogendoorn forgot to respond to this. We are looking into this a.s.a.p.

**Comment by Buckaroo-Rens** [comment]
@meeshoogendoorn That's right, I just wanted to confirm if this fix works for you too.
